# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: number_image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12number_image.proto\"/\n\x0bNumberImage\x12\x11\n\tDataArray\x18\x01 \x01(\x0c\x12\r\n\x05Value\x18\x02 \x01(\x05\"\x1a\n\tIntNumber\x12\r\n\x05Value\x18\x01 \x01(\x05\x32w\n\x0fMachineLearning\x12\x32\n\x14GetRandomNumberImage\x12\n.IntNumber\x1a\x0c.NumberImage\"\x00\x12\x30\n\x12PredictNumberImage\x12\x0c.NumberImage\x1a\n.IntNumber\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'number_image_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NUMBERIMAGE']._serialized_start=22
  _globals['_NUMBERIMAGE']._serialized_end=69
  _globals['_INTNUMBER']._serialized_start=71
  _globals['_INTNUMBER']._serialized_end=97
  _globals['_MACHINELEARNING']._serialized_start=99
  _globals['_MACHINELEARNING']._serialized_end=218
# @@protoc_insertion_point(module_scope)
