# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import number_image_pb2 as number__image__pb2


class MachineLearningStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRandomNumberImage = channel.unary_unary(
                '/MachineLearning/GetRandomNumberImage',
                request_serializer=number__image__pb2.IntNumber.SerializeToString,
                response_deserializer=number__image__pb2.NumberImage.FromString,
                )
        self.PredictNumberImage = channel.unary_unary(
                '/MachineLearning/PredictNumberImage',
                request_serializer=number__image__pb2.NumberImage.SerializeToString,
                response_deserializer=number__image__pb2.IntNumber.FromString,
                )


class MachineLearningServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRandomNumberImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictNumberImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MachineLearningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRandomNumberImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRandomNumberImage,
                    request_deserializer=number__image__pb2.IntNumber.FromString,
                    response_serializer=number__image__pb2.NumberImage.SerializeToString,
            ),
            'PredictNumberImage': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictNumberImage,
                    request_deserializer=number__image__pb2.NumberImage.FromString,
                    response_serializer=number__image__pb2.IntNumber.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MachineLearning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MachineLearning(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRandomNumberImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MachineLearning/GetRandomNumberImage',
            number__image__pb2.IntNumber.SerializeToString,
            number__image__pb2.NumberImage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PredictNumberImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MachineLearning/PredictNumberImage',
            number__image__pb2.NumberImage.SerializeToString,
            number__image__pb2.IntNumber.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
