; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28315.0 

	TITLE	B:\02_ONLINE\03_WINDOWS\SOURCE\ASSEMBLY\CPP\square.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_square
; Function compile flags: /Odtp
; File B:\02_ONLINE\03_WINDOWS\SOURCE\ASSEMBLY\CPP\square.c
_TEXT	SEGMENT
_a$ = 8							; size = 4
_square	PROC

; 3    : {

	push	ebp
	mov	ebp, esp

; 4    : 	return a * a;

	mov	eax, DWORD PTR _a$[ebp]
	imul	eax, DWORD PTR _a$[ebp]

; 5    : }

	pop	ebp
	ret	0
_square	ENDP
_TEXT	ENDS
END
