; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28314.0 

	TITLE	B:\02_ONLINE\03_WINDOWS\SOURCE\ASSEMBLY\STACKFRAME\sample.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_add
PUBLIC	_main
; Function compile flags: /Odtp
; File B:\02_ONLINE\03_WINDOWS\SOURCE\ASSEMBLY\STACKFRAME\sample.c
_TEXT	SEGMENT
_n$ = -4						; size = 4
_main	PROC

; 11   : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 12   : 	int n = add(1, 2);

	push	2
	push	1
	call	_add
	add	esp, 8
	mov	DWORD PTR _n$[ebp], eax

; 13   : }

	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File B:\02_ONLINE\03_WINDOWS\SOURCE\ASSEMBLY\STACKFRAME\sample.c
_TEXT	SEGMENT
_d$ = -8						; size = 4
_c$ = -4						; size = 4
_a$ = 8							; size = 4
_b$ = 12						; size = 4
_add	PROC

; 4    : {

	push	ebp
	mov	ebp, esp
	sub	esp, 8

; 5    : 	int c = 0;

	mov	DWORD PTR _c$[ebp], 0

; 6    : 	int d = 0;

	mov	DWORD PTR _d$[ebp], 0

; 7    : 	c = a + b;

	mov	eax, DWORD PTR _a$[ebp]
	add	eax, DWORD PTR _b$[ebp]
	mov	DWORD PTR _c$[ebp], eax

; 8    : 	return c;

	mov	eax, DWORD PTR _c$[ebp]

; 9    : }

	mov	esp, ebp
	pop	ebp
	ret	0
_add	ENDP
_TEXT	ENDS
END
